services:
  - type: web
    name: ecommerce-chatbot
    runtime: python
    plan: free
    rootDir: ecommerce_streamlit_app
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5